name: GitHub Actions Demo
on:
  push:
    branches:
      - main  # Adjust as per your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Backend steps
      - name: Set up JDK 22.0.1
        uses: actions/setup-java@v3
        with:
          java-version: '22.0.1'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and test backend
        working-directory: ./backend
        run: |
          mvn clean install -DskipTests
          mvn test

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifacts
          path: ./backend/target/*.jar

      - name: Deploy to Render
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$DEPLOY_URL"
